src/Site/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using School.Application.Interfaces;
using School.Application.ViewModels;

namespace School.Site.Controllers
{
    public class CourseController : BaseController
    {
        private readonly INotification _notification;
        private readonly ICourseService _service;

        public CourseController(INotification notification, ICourseService service) : base(notification)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _service.ListAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _service.GetAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var model = id == null
                ? new CourseViewModel()
                : await _service.GetAsync(id.Value);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection collection)
        {
            var model = new CourseViewModel();
            if (!await TryUpdateModelAsync(model))
                _notification.Add("There was an error while trying to validate the form.");

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Id == Guid.Empty)
                        _service.Add(model);
                    else
                        _service.Update(model);

                    if(ValidOperation())
                        return RedirectToAction("Index");
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return View(model);
        }
    }
}

src/Site/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using School.Application.Interfaces;
using School.Application.ViewModels;

namespace School.Site.Controllers
{
    public class StudentController : BaseController
    {
        private readonly INotification _notification;
        private readonly IStudentService _service;

        public StudentController(INotification notification, IStudentService service) 
            : base(notification)
        {
            _notification = notification;
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _service.ListAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _service.GetAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var model = id == null
                ? new StudentViewModel()
                : await _service.GetAsync(id.Value);

            TempData["Courses"] = JsonConvert.SerializeObject(model.Courses);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection collection)
        {
            var model = new StudentViewModel();

            if (!await TryUpdateModelAsync(model))
                _notification.Add("There was an error while trying to validate the form.");

            if (ModelState.IsValid)
            {
                try
                {
                    model.Courses = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);

                    if (model.Id == Guid.Empty)
                        _service.Add(model);
                    else
                        _service.Update(model);

                    if(ValidOperation())
                        return RedirectToAction("Index");
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return View(model);
        }

        public IActionResult FindCourses()
        {
            var model = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);
            return PartialView("_ListCourses", model);
        }

        public async Task<IActionResult> ListCourses()
        {
            var model = await _service.ListCoursesAsync();
            return PartialView("_Courses", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCourse(Guid id)
        {
            var courses = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);

            if (!courses.Any(p => p.Id == id))
            {
                var course = await _service.GetCoursesAsync(id);
                courses.Add(course);
                TempData["Courses"] = JsonConvert.SerializeObject(courses);
                return Json(new { result = true });
            }            

            return Json(new { result = false });
        }

        [HttpPost]
        public IActionResult RemoveCourse(Guid id)
        {
            var courses = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);
            var course = courses.FirstOrDefault(p => p.Id == id);

            if (course != null)
            {                
                courses.Remove(course);
                TempData["Courses"] = JsonConvert.SerializeObject(courses);
                return Json(new { result = true });
            }

            return Json(new { result = false });
        }
    }
}

src/Site/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Application.Interfaces;
using School.Application.ViewModels;

namespace School.Site.Controllers
{
    public class TeacherController : BaseController
    {
        private readonly INotification _notification;
        private readonly ITeacherService _service;

        public TeacherController(INotification notification, ITeacherService service) 
            : base(notification)
        {
            _notification = notification;
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _service.ListAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _service.GetAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var model = id == null
                ? new TeacherViewModel()
                : await _service.GetAsync(id.Value);

            await LoadViewData();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection collection)
        {
            var model = new TeacherViewModel();
            if (!await TryUpdateModelAsync(model))
                _notification.Add("There was an error while trying to validate the form.");

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Id == Guid.Empty)
                        _service.Add(model);
                    else
                        _service.Update(model);

                    if(ValidOperation())
                        return RedirectToAction("Index");
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            await LoadViewData();
            return View(model);
        }

        private async Task LoadViewData()
        {
            ViewBag.Courses = new SelectList(await _service.ListCourseAsync(), "Id", "Name");
        }
    }
}

src/Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/vendor/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/vendor/datatables.net-dt/css/jquery.dataTables.css" />
        <link rel="stylesheet" href="~/vendor/datatables.net-buttons-dt/css/buttons.dataTables.css" />
        <link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>

    <partial name="_Navbar" />
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - School</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/vendor/jquery/dist/jquery.js"></script>
        <script src="~/vendor/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/vendor/datatables.net/js/jquery.dataTables.js"></script>
        <script src="~/vendor/datatables.net-dt/js/dataTables.dataTables.js"></script>
        <script src="~/vendor/datatables.net-buttons/js/dataTables.buttons.js"></script>
        <script src="~/vendor/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/vendor/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
        <script src="~/vendor/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    </environment>
    
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Site/Views/Shared/_LayoutClear.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/vendor/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/vendor/jquery/dist/jquery.js"></script>
        <script src="~/vendor/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/Site/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" asp-action="Index" asp-controller="Home">School</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Course" class="nav-link">Course</a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Teacher" class="nav-link">Teacher</a>
            </li>
            <li class="nav-item">
                <a asp-action="Index" asp-controller="Student" class="nav-link">Student</a>
            </li>
        </ul>
    </div>
</nav>