src/Site/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using School.Application.Interfaces;
using School.Application.ViewModels;

namespace School.Site.Controllers
{
    public class CourseController : BaseController
    {
        private readonly INotification _notification;
        private readonly ICourseService _service;

        public CourseController(INotification notification, ICourseService service) : base(notification)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _service.ListAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _service.GetAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var model = id == null
                ? new CourseViewModel()
                : await _service.GetAsync(id.Value);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection collection)
        {
            var model = new CourseViewModel();
            if (!await TryUpdateModelAsync(model))
                _notification.Add("There was an error while trying to validate the form.");

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Id == Guid.Empty)
                        _service.Add(model);
                    else
                        _service.Update(model);

                    if(ValidOperation())
                        return RedirectToAction("Index");
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return View(model);
        }
    }
}

src/Site/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using School.Application.Interfaces;
using School.Application.ViewModels;

namespace School.Site.Controllers
{
    public class StudentController : BaseController
    {
        private readonly INotification _notification;
        private readonly IStudentService _service;

        public StudentController(INotification notification, IStudentService service) 
            : base(notification)
        {
            _notification = notification;
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _service.ListAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _service.GetAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var model = id == null
                ? new StudentViewModel()
                : await _service.GetAsync(id.Value);

            TempData["Courses"] = JsonConvert.SerializeObject(model.Courses);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection collection)
        {
            var model = new StudentViewModel();

            if (!await TryUpdateModelAsync(model))
                _notification.Add("There was an error while trying to validate the form.");

            if (ModelState.IsValid)
            {
                try
                {
                    model.Courses = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);

                    if (model.Id == Guid.Empty)
                        _service.Add(model);
                    else
                        _service.Update(model);

                    if(ValidOperation())
                        return RedirectToAction("Index");
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return View(model);
        }

        public IActionResult FindCourses()
        {
            var model = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);
            return PartialView("_ListCourses", model);
        }

        public async Task<IActionResult> ListCourses()
        {
            var model = await _service.ListCoursesAsync();
            return PartialView("_Courses", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCourse(Guid id)
        {
            var courses = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);

            if (!courses.Any(p => p.Id == id))
            {
                var course = await _service.GetCoursesAsync(id);
                courses.Add(course);
                TempData["Courses"] = JsonConvert.SerializeObject(courses);
                return Json(new { result = true });
            }            

            return Json(new { result = false });
        }

        [HttpPost]
        public IActionResult RemoveCourse(Guid id)
        {
            var courses = JsonConvert.DeserializeObject<List<CourseViewModel>>(TempData.Peek("Courses") as string);
            var course = courses.FirstOrDefault(p => p.Id == id);

            if (course != null)
            {                
                courses.Remove(course);
                TempData["Courses"] = JsonConvert.SerializeObject(courses);
                return Json(new { result = true });
            }

            return Json(new { result = false });
        }
    }
}

src/Site/ViewComponents/SummaryViewComponent.cs
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace School.Site.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotification _notifications;

        public SummaryViewComponent(INotification notifications)
        {
            _notifications = notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.Notifications);
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Description));

            return View();
        }
    }
}

src/Site/Views/Student/Details.cshtml
@model School.Application.ViewModels.StudentViewModel

@{
    ViewData["Title"] = "Details";
}
<h4 class="page-header">@ViewData["Title"]</h4>
<hr />
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="form-group col-md-4">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" readonly />
            </div>
            <div class="form-group col-md-4">
                <label asp-for="BirthDate"></label>
                <input asp-for="BirthDate" class="form-control" readonly />
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" readonly />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" readonly />
            </div>

        </div>
    </div>
    <div class="card-footer">
        <div class="btn-group">
            <a asp-action="Edit" asp-route-id=@Model.Id class="btn btn-outline-secondary">Edit</a>
            <a asp-action="Index" class="btn btn-outline-dark">Back to list</a>
        </div>
    </div>
</div>

src/Site/Views/Student/Edit.cshtml
@model School.Application.ViewModels.StudentViewModel

@{
    ViewData["Title"] = "Edit";
}
<h4 class="page-header">@ViewData["Title"]</h4>
<hr />
<form asp-action="Edit">
    <div class="card">
        <div class="card-body">
            <vc:summary></vc:summary>
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="form-group col-md-4">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="BirthDate"></label>
                    <input asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div id="list-courses">
                        @{ await Html.RenderPartialAsync("_ListCourses", Model.Courses); }
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="form-group">
                <div class="btn-group">
                    <input type="submit" value="Confirm" class="btn btn-outline-success" />
                    <a asp-action="Index" class="btn btn-outline-dark">Back to list</a>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="modal fade" id="course-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="z-index: 9999999999">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div id="course-form">
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        // Endereço
        function openModal() {
            $("#course-modal").modal();
        }

        function getCourses() {
            $.ajax({
                type: "GET",
                url: "@Url.Action("FindCourses")",
                dataType: "html",
                success: function (data) {
                    $("#list-courses").html(data);
                },
                error: function (e) {
                    alert(e);
                }
            });
        }
    </script>
}

src/Site/Views/Student/Index.cshtml
@model IEnumerable<School.Application.ViewModels.StudentViewModel>

@{
    ViewData["Title"] = "Index";
}

<h4 class="panel-title">@ViewData["Title"]</h4>
<hr />
<div class="btn-group m-3 role="group">
    <a asp-action="Edit" class="btn btn-outline-primary"><span class="glyphicon glyphicon-plus"></span> Add </a>
    <a asp-action="Edit" class="btn btn-outline-secondary" data-button="edit"><span class="glyphicon glyphicon-pencil"></span> Edit </a>
    <a asp-action="Details" class="btn btn-outline-info" data-button="details"><span class="glyphicon glyphicon-search"></span> Details </a>
</div>
<table class="table table-striped table-bordered data-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr data-href="@Url.Action("Edit", new { id=item.Id })" data-href-details="@Url.Action("Details", new { id=item.Id })" >
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
        </tr>
        }
    </tbody>
</table>

src/Site/Views/Student/_Courses.cshtml
@model IEnumerable<School.Application.ViewModels.CourseViewModel>

<div class="modal-header">
    <h4 class="modal-title"><span class="fa fa-book"></span> Courses </h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>

<div class="row">
    <div class="col m-3">
        <table class="table table-striped table-bordered data-table">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="5px">
                            <a asp-action="AddCourse" asp-route-id="@item.Id" class="btn btn-sm btn-outline-primary"
                               data-ajax="true"
                               data-ajax-method="POST"
                               data-ajax-success="getCourses">
                            <span class="fa fa-plus"></span> 
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ListScriptsPartial");}
}

src/Site/Views/Student/_ListCourses.cshtml
@model IEnumerable<School.Application.ViewModels.CourseViewModel>

<div class="m-3">
    <a asp-controller="Student"
       asp-action="ListCourses"
       class="btn btn-primary"
       data-ajax="true"
       data-ajax-method="GET"
       data-ajax-mode="replace"
       data-ajax-update="#course-form"
       data-ajax-success="openModal"
       data-ajax-failure="notifyFailure"><span class="glyphicon glyphicon-plus"></span>Add Course</a>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="5px">
                    <a asp-action="RemoveCourse" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger"
                       data-ajax="true"
                       data-ajax-method="POST"
                       data-ajax-success="getCourses">
                        <span class="fa fa-minus"></span>
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        function notifyFailure() {
            alert("Failed to open window.");
        }
    </script>
}