src/Site/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using School.Application.Interfaces;
using School.Application.ViewModels;

namespace School.Site.Controllers
{
    public class SecurityController : BaseController
    {
        private readonly INotification _notification;
        private readonly IIdentityService _service;

        public SecurityController(INotification notification, IIdentityService service) 
            : base(notification)
        {
            _notification = notification;
            _service = service;
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(IFormCollection collection)
        {
            var model = new LoginViewModel();

            if (!await TryUpdateModelAsync(model))
            {
                _notification.Add("Could not validate form.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.LoginAsync(model);
                    if (ValidOperation())
                        return RedirectToAction("Index", "Home");
                }
                catch (Exception exception)
                {
                    _notification.Add(exception.Message);
                }
            }

            return View(model);
        }

        [AllowAnonymous]
        [Route("register-user")]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [Route("register-user")]
        public async Task<IActionResult> Register(IFormCollection collection)
        {
            var model = new RegisterViewModel();

            if (!await TryUpdateModelAsync(model))
            {
                _notification.Add("Could not validate form.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.Register(model);
                    if (ValidOperation())
                        return RedirectToAction("Login");
                }
                catch (Exception exception)
                {
                    _notification.Add(exception.Message);
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await _service.LogoutAsync();
            return RedirectToAction("Login");
        }
    }
}

src/Site/ViewComponents/SummaryViewComponent.cs
using DDD.Shared.Notifications.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace School.Site.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotification _notifications;

        public SummaryViewComponent(INotification notifications)
        {
            _notifications = notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.Notifications);
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Description));

            return View();
        }
    }
}

src/Site/Views/Security/Login.cshtml
@model School.Application.ViewModels.LoginViewModel

@{
    ViewData["Title"] = "Login";
    Layout = "_LayoutClear";
}

<section>
    <div class="card card-login mx-auto">
        <h3 class="card-header">@ViewData["Title"]</h3>
        <div class="card-body">
            <form asp-controller="Security" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <vc:summary></vc:summary>
                <div class="row">
                    <div class="form-group col-md-12">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" placeholder="E-mail" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Password"></label>
                        <input asp-for="Password" class="form-control" placeholder="Password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-lg btn-primary btn-block">Login</button>
                    </div>
                    <div class="col-md-6 text-center">
                        <a asp-action="Register">New user</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row mx-auto">
        <div class="col-md-5 col-md-offset-4">

        </div>
    </div>
</section>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/Site/Views/Security/Register.cshtml
@model School.Application.ViewModels.RegisterViewModel

@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_LayoutClear.cshtml";
}
<h4 class="page-header">@ViewData["Title"]</h4>
<hr />
<form asp-action="Register">
    <div class="card">
        <div class="card-body">
            <vc:summary></vc:summary>
            <div class="row">
                <div class="form-group col-md-4">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label asp-for="ConfirmPassword"></label>
                    <input asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="form-group">
                <div class="btn-group">
                    <input type="submit" value="Confirm" class="btn btn-outline-success" />
                    <a asp-action="Login" class="btn btn-outline-dark">Login</a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}